PROJECTNAME = GameLumine
OUTPUT_DIR = out

INCLUDE_DIRS = -I include/SDL2 -Iinclude/imgui -Iinclude
LIB_DIRS = -L lib

ARGS = -Wall -Wextra -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Bdynamic -pipe

ARGS_ = -Wall -Wextra -O3 -static-libgcc -static-libstdc++ -Wl,-Bstatic -lstdc++ -lpthread -Bdynamic -pipe -mwindows 

LIBS = -lmingw32 -lSDL2main -lSDL2 -lnfd_d -lole32 -lcomctl32 -luuid -lwinmm -lgdi32 -loleaut32 -lcfgmgr32 -limm32 -lversion -lsetupapi

SRC = $(wildcard src/*.cpp)  $(wildcard imgui/*.cpp) $(wildcard imgui/*.c) $(wildcard src/screens/*.cpp) 

default:
	g++ $(SRC) -o $(OUTPUT_DIR)/$(PROJECTNAME) $(ARGS_) $(INCLUDE_DIRS) $(LIB_DIRS) $(LIBS)
